### ISSUE TITLE
Add system shortcut to open app

### ISSUE THREAD

**Issue by heitortsergent** [kunal732/MacLexa#6]

**Comment by kunal732** [comment]
can you explain a little more what you mean ? The way I see it is the app is always running in the system tray and you just activate it by pressing the option key. 

Are you trying to launch the app when your computer turns on ?

**Comment by heitortsergent** [comment]
Oooooh, my bad. I thought you had to click on the tray icon before being able to use it. 

I'm just going to +1 #2 then. :)
